# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v13.0.0'
  hooks:
  - id: clang-format

- repo: https://github.com/maxwinterstein/shfmt-py
  rev: 3.3.1.8
  hooks:
    - id: shfmt
      # We force python3.9 since as of its current version `shfmt-py` has a
      # `setup.cfg` not conforming to PEP639 (`license_file` instead of
      # `license_files`) which triggers a warning with newer Python versions.
      language_version: "3.9"
      args: ["-w", "-i", "4", "-ci"]

- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.31.0
  hooks:
  - id: yapf

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    exclude: '^auxil/.*$'
