name: GitHub Builds

on:
  pull_request:


permissions: read-all

env:
    ZEEK_CI_CPUS: 2
    ZEEK_CI_BTEST_JOBS: 4
    ZEEK_CI_CONFIGURE_FLAGS: '--build-type=Release --disable-broker-tests --prefix=/opt/zeek --ccache'
    ZEEK_CI_BTEST_RETRIES: 2
    HILTI_CXX_COMPILER_LAUNCHER: ccache

    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub debug
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}

  fedora-38:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
    - name: Do we have environment variables?
      run: env

    # There's also https://github.com/hendrikmuhs/ccache-action
    #
    # Max caches per repo: 10GB. Pruned after 7 days.
    #
    # Caches in branches are isolated, but use existing caches
    # from the main or base branch. Restoration of the most recent
    # cache wherever found.
    #
    # Forcefully evicting caches when PRs are closed to avoid thrashing:
    # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
    # - name: ccache setup
    #  uses: actions/cache@v3.3.1
    #  with:
    #    path: /tmp/ccache
    #    key: ${{ github.job }}-ccache
    #
    - name: Install dependencies (could pre-built CI images instead?)
      run: |
        dnf -y install \
          bison \
          ccache \
          cmake \
          diffutils \
          findutils \
          flex \
          gcc \
          gcc-c++ \
          git \
          libpcap-devel \
          make \
          nodejs-devel \
          openssl \
          openssl-devel \
          procps-ng \
          python3 \
          python3-devel \
          python3-pip\
          sqlite \
          swig \
          which \
          zlib-devel

    - uses: actions/cache/restore@v3
      id: ccache-restore
      with:
        path: /tmp/ccache
        key: ${{ runner.os }}-${{ github.job }}-ccache

    - name: nproc and lscpu
      run: nproc; lscpu; true

    - name: Checkout repo with submodules (could be prepped/cached via artifacts?)
      uses: actions/checkout@v3
      with:
        submodules: recursive
    # Isn't there a better fix?
    - name: Fix dubious ownership.
      run: git config --global --add safe.directory /__w/zeek/zeek
    - name: Test repo
      run: git rev-parse --is-inside-work-tree
    - name: Pre-test collect-repo-info.py
      run: ./ci/collect-repo-info.py
    - name: Init external repos
      run: ./ci/init-external-repos.sh
    - name: Configure
      run: ./configure $ZEEK_CI_CONFIGURE_FLAGS
    - name: Build
      run: cd build && make -j${ZEEK_CI_CPUS}
    - name: Show ccache stats
      run: ccache --show-stats

    - name: Save ccache files
      uses: actions/cache/save@v3
      id: ccache-save
      with:
        path: /tmp/ccache
        key: ${{ runner.os }}-${{ github.job }}-ccache-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Btest testing
      run: ./ci/test.sh

  debian-12:
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
    - name: Do we have environment variables?
      run: env

    - name: Install dependencies (could pre-built CI images instead?)
      run: |
        apt-get update && apt-get -y install \
          bison \
          bsdmainutils \
          ccache \
          cmake \
          curl \
          flex \
          g++ \
          gcc \
          git \
          libkrb5-dev \
          libnode-dev \
          libpcap-dev \
          libssl-dev \
          libuv1-dev \
          make \
          python3 \
          python3-dev \
          python3-pip\
          python3-websockets \
          sqlite3 \
          swig \
          wget \
          xz-utils \
          zlib1g-dev

    - uses: actions/cache/restore@v3
      id: ccache-restore
      with:
        path: /tmp/ccache
        key: ${{ runner.os }}-${{ github.job }}-ccache

    - name: nproc and lscpu
      run: nproc; lscpu; true

    - name: Checkout repo with submodules (could be prepped/cached via artifacts?)
      uses: actions/checkout@v3
      with:
        submodules: recursive
    # Isn't there a better fix?
    - name: Fix dubious ownership.
      run: git config --global --add safe.directory /__w/zeek/zeek
    - name: Test repo
      run: git rev-parse --is-inside-work-tree
    - name: Pre-test collect-repo-info.py
      run: ./ci/collect-repo-info.py
    - name: Init external repos
      run: ./ci/init-external-repos.sh
    - name: Configure
      run: ./configure $ZEEK_CI_CONFIGURE_FLAGS
    - name: Build
      run: cd build && make -j${ZEEK_CI_CPUS}
    - name: Show ccache stats
      run: ccache --show-stats

    - name: Save ccache files
      uses: actions/cache/save@v3
      id: ccache-save
      with:
        path: /tmp/ccache
        key: ${{ runner.os }}-${{ github.job }}-ccache-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Btest testing
      run: ./ci/test.sh
