name: builds

on:
  pull_request:


permissions: read-all

env:
    WORKING_DIR: /github-zeek
    ZEEK_CI_CPUS: 2
    ZEEK_CI_BTEST_JOBS: 4
    ZEEK_CI_CONFIGURE_FLAGS: '--build-type=release --disable-broker-tests --prefix=$WORKING_DIR/install --ccache'
    HILTI_CXX_COMPILER_LAUNCHER: ccache

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub debug
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}

  #   name: Prepare
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@master
  #     with:
  #       submodules: recursive

  fedora-38:
    runs-on: ubuntu-latest
    container:
      image: fedora:38
    steps:
    - name: Do we have environment variables?
      run: env
    - name: Install dependencies (could pre-built CI images instead?)
      run: |
        dnf -y install \
          bison \
          ccache \
          cmake \
          diffutils \
          findutils \
          flex \
          gcc \
          gcc-c++ \
          git \
          libpcap-devel \
          make \
          nodejs-devel \
          openssl \
          openssl-devel \
          procps-ng \
          python3 \
          python3-devel \
          python3-pip\
          sqlite \
          swig \
          which \
          zlib-devel
    - name: nproc and lscpu
      run: nproc; lscpu; true

    - name: Checkout repo with submodules (could be prepped/cached?)
      uses: actions/checkout@v3
      with:
        submodules: recursive
    # Isn't there a better fix?
    - name: Fix dubious ownership.
      run: git config --global --add safe.directory /__w/zeek/zeek
    - name: Test repo
      run: git rev-parse --is-inside-work-tree
    - name: Pre-test collect-repo-info.py
      run: ./ci/collect-repo-info.py
    # This is all in ci/build.sh, but references a bit of CIRRUS stuff.
    - name: Configure
      run: ./configure $ZEEK_CI_CONFIGURE_FLAGS
    - name: Build
      run: cd build && make -j${ZEEK_CI_CPUS}
    - name: Btest testing
      run: cd testing/btest && ../../auxil/btest/btest -A -d -j ${ZEEK_CI_BTEST_JOBS}
